name: Publish package to GitHub

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.email "marcel.lorke@gmail.com"
          git config user.name "Marcel Lorke"
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish package to GitHub
        run: mvn -V -B -X release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}
